try {
  console.log(a);
  let a = 3;
} catch {
  console.log("let перед использованием нужно обьявить");
}
